/**
 * Copyright Chinmay Anand. All Rights Reserved.
 * Main tester class generated by spring starter.
 * @author Chinmay
 *
 */

package com.chinmay.aws_dynamo_sms;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class AwsDynamoSmsApplicationTests {

	@Test
	void contextLoads() {
	}

}
